"""Add verification fields to User

Revision ID: 28071cfe298e
Revises: a806f97725fb
Create Date: 2026-04-12 22:26:20.284635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28071cfe298e'
down_revision: Union[str, Sequence[str], None] = 'a806f97725fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verification_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verification_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_data')
    op.drop_column('users', 'verification_status')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
