"""Add specialist fields and service categories

Revision ID: 973b8d5ee091
Revises: 81a10632785a
Create Date: 2026-04-14 11:36:18.947522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '973b8d5ee091'
down_revision: Union[str, Sequence[str], None] = '81a10632785a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_categories_id'), 'service_categories', ['id'], unique=False)
    op.create_index(op.f('ix_service_categories_name'), 'service_categories', ['name'], unique=True)
    op.create_table('user_services',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'service_id')
    )
    op.add_column('users', sa.Column('birth_year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('education_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('workplace', sa.String(), nullable=True))
    op.add_column('users', sa.Column('service_location_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))
    op.drop_column('users', 'subscription_tier')
    op.drop_column('users', 'subscription_expires_at')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('subscription_expires_at', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('subscription_tier', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'service_location_name')
    op.drop_column('users', 'workplace')
    op.drop_column('users', 'education_level')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'birth_year')
    op.drop_table('user_services')
    op.drop_index(op.f('ix_service_categories_name'), table_name='service_categories')
    op.drop_index(op.f('ix_service_categories_id'), table_name='service_categories')
    op.drop_table('service_categories')
    # ### end Alembic commands ###
