"""Add subscription fields to User

Revision ID: b2f0a07c9616
Revises: de7fb3a64872
Create Date: 2026-04-12 22:39:01.293669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f0a07c9616'
down_revision: Union[str, Sequence[str], None] = 'de7fb3a64872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_tier', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_expires_at')
    op.drop_column('users', 'subscription_tier')
    # ### end Alembic commands ###
